### ISSUE TITLE
Import photo dans une citation - message d'erreur

### ISSUE THREAD

**Issue by Vottana** [picardie-nature/clicnat-public-v1#34]
Message d'erreur lorsque l'on tente d'importer une photo pour accompagner une citation.
![erreur_import_photo](https://cloud.githubusercontent.com/assets/15034095/10390243/b1abc8f8-6e77-11e5-8d43-40cc79b89bad.jpg)

**Comment by ndamiens** [comment]
Salut,

Tu peux essayer à nouveau (ps c'est pas le bon dépôt, la bonne adresse : https://github.com/picardie-nature/baseobs/ )
